server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: louiemain
    url: jdbc:mysql://localhost:3306/ihc_dev?useSSL=true&useUnicode=true&characterEncoding=utf-8
