server:
  port: 80
web:
  printTablePath: C:/Program Files (x86)/SMF/Files/
#  子公司代码
sub:
  name: guizhou
  code: K2011011
spring:
  mvc:
    static-path-pattern: /**
# 加入所有静态资源路径（覆盖默认配置）
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/json/,classpath:/public/,file:${web.printTablePath}
#  启动模式（java -jar ihc-0.0.1-SNAPSHOT.jar --spring.profiles.active=dev）
  profiles:
    active: dev